// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUiqvYKhXfdM4O8gHBwZojsueyYrkwALg',
    appId: '1:223841487849:web:79454dfc7f13dc9f6f9978',
    messagingSenderId: '223841487849',
    projectId: 'controladorremedios',
    authDomain: 'controladorremedios.firebaseapp.com',
    storageBucket: 'controladorremedios.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABg0beIQq9l5vNEp6_MxAx85ejA0p2sjY',
    appId: '1:223841487849:android:66e5e7e795a32cc76f9978',
    messagingSenderId: '223841487849',
    projectId: 'controladorremedios',
    storageBucket: 'controladorremedios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKX-mW6ODESLvbeuwYDNuZtKONTa-P5E',
    appId: '1:223841487849:ios:607ebadc435ab7a26f9978',
    messagingSenderId: '223841487849',
    projectId: 'controladorremedios',
    storageBucket: 'controladorremedios.appspot.com',
    iosBundleId: 'com.example.appplotzeTrabalho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFKX-mW6ODESLvbeuwYDNuZtKONTa-P5E',
    appId: '1:223841487849:ios:0785bd6bef7d20e76f9978',
    messagingSenderId: '223841487849',
    projectId: 'controladorremedios',
    storageBucket: 'controladorremedios.appspot.com',
    iosBundleId: 'com.example.appplotzeTrabalho.RunnerTests',
  );
}
